import { useState, useRef, useCallback, useEffect } from "react";
import { Play, User, Bell, Shield, KeyRound, CreditCard, Plus, LayoutGrid, Hash, Clock3 } from "lucide-react";
import * as XLSX from "xlsx";
import "./DocExtract.css";
import { History } from "./history";
import { Dashboard } from "./Dashboard";


// ── PRESETS ───────────────────────────────────────────────────────────────────
const PRESETS_POLICY_CHECKING = [
  {
    label: "Policy Number",
    field: "Policy Number",
    prompt: "Extract the policy number exactly as it appears. Return only the policy number string, no surrounding text.",
  },
  {
    label: "Name Insured",
    field: "Name Insured",
    prompt: "Extract the primary named insured. Return the full legal name as a string.",
  },
  {
    label: "Policy Period",
    field: "Policy Period",
    prompt: "Extract the policy period dates. Return in format MM/DD/YYYY to MM/DD/YYYY.",
  },
  {
    label: "Premium",
    field: "Premium",
    prompt: "Extract the total premium amount including any breakdowns. Return as a string with dollar sign.",
  },
  {
    label: "Issuing Company",
    field: "Issuing Company",
    prompt: "Extract the name of the insurance company issuing this policy.",
  },
  {
    label: "Mailing Address",
    field: "Mailing Address",
    prompt: "Extract the mailing address of the named insured. Return as a single formatted address string.",
  },
  {
    label: "Deductible",
    field: "Deductible",
    prompt: "Extract all deductible amounts and types. Return as a string or object with labels and values.",
  },
  {
    label: "Endorsements",
    field: "Endorsements",
    prompt: "Extract all endorsements — list changes, additions, deletions, and modifications. Return as an array of strings.",
  },
  {
    label: "Forms & Endorsements",
    field: "Forms and Endorsements",
    prompt: "Extract all form numbers and titles from the Forms and Endorsements section. Format each as: FormNumber | MM/YY Form Title. Return as array.",
  },
];

const PRESETS_FINANCE = [
  {
    label: "Revenue",
    field: "Revenue",
    prompt: "Extract the total revenue or total income for the period from the Profit & Loss statement or Income Statement. Look for 'Total Revenue', 'Total Income', 'Net Revenue', or 'Revenue from operations'. Return only the numerical value."
  },
  {
    label: "Net Income",
    field: "Net Income",
    prompt: "Extract the net income or profit attributable to shareholders from the Profit & Loss statement. Look for 'Net Income', 'Profit for the period', 'Profit after tax', or 'Earnings for the period'. Return only the numerical value."
  },
  {
    label: "Gross Profit",
    field: "Gross Profit",
    prompt: "Extract gross profit from the Profit & Loss statement. Look for 'Gross Profit' line item. Return only the numerical value."
  },
  {
    label: "Operating Income",
    field: "Operating Income",
    prompt: "Extract operating income from the Profit & Loss statement. Look for 'Operating Income', 'Operating Profit', 'EBIT', or 'Profit before depreciation'. Return only the numerical value."
  },
  {
    label: "EBITDA",
    field: "EBITDA",
    prompt: "Extract EBITDA if explicitly stated in the document. If not found calculate them."
  },
  {
    label: "Cost of Goods Sold",
    field: "Cost of Goods Sold",
    prompt: "Extract the cost of goods sold (COGS) from the Profit & Loss statement. Return only the numerical value."
  },
  {
    label: "Total Debt",
    field: "Total Debt",
    prompt: "Extract total debt from the Balance Sheet. This is the sum of long-term debt, current maturities of long-term debt, and short-term borrowings. Return only the total numerical value."
  },
  {
    label: "Interest Expense",
    field: "Interest Expense",
    prompt: "Extract total interest expense from the Profit & Loss statement. Look for 'Interest Expense' or 'Finance costs'. Return only the numerical value."
  },
  {
    label: "Cash and Cash Equivalents",
    field: "Cash and Cash Equivalents",
    prompt: "Extract cash and cash equivalents from the Balance Sheet under Current Assets. Look for 'Cash and cash equivalents' or similar. Return only the numerical value."
  },
  {
    label: "Operating Cash Flow",
    field: "Operating Cash Flow",
    prompt: "Extract the net cash from operating activities from the Cash Flow Statement. Look for 'Net Cash Generated by Operating Activities' or similar. Return only the numerical value."
  },
  {
    label: "Capital Expenditure",
    field: "Capital Expenditure",
    prompt: "Extract capital expenditure from the Cash Flow Statement under Investing Activities. Look for 'Payment towards capital expenditure' or 'Capital Expenditure'. Return only the numerical value."
  },
  {
    label: "Free Cash Flow",
    field: "Free Cash Flow",
    prompt: "Extract free cash flow if explicitly stated in the document. If not found, return null. Do NOT calculate it."
  },
  {
    label: "Total Assets",
    field: "Total Assets",
    prompt: "Extract total assets from the Balance Sheet. Look for the 'Total Assets' line at the end of the assets section. Return only the numerical value."
  },
  {
    label: "Total Liabilities",
    field: "Total Liabilities",
    prompt: "Extract total liabilities from the Balance Sheet. Look for the total of all current and non-current liabilities. Return only the numerical value."
  },
  {
    label: "Current Assets",
    field: "Current Assets",
    prompt: "Extract current assets from the Balance Sheet. Look for 'Total Current Assets' line. Return only the numerical value."
  },
  {
    label: "Current Liabilities",
    field: "Current Liabilities",
    prompt: "Extract current liabilities from the Balance Sheet. Look for 'Total Current Liabilities' line. Return only the numerical value."
  },
  {
    label: "Company Name",
    field: "Company Name",
    prompt: "Extract the full legal name of the company as it appears at the top of the financial statements."
  },
  {
    label: "Fiscal Year",
    field: "Fiscal Year",
    prompt: "Extract the fiscal year or reporting year from the financial statement. Return as YYYY (e.g., 2024)."
  },
  {
    label: "period",
    field: "Period",
    prompt: "Extract the exact reporting period from the financial statement. Return in format 'Month DD, YYYY to Month DD, YYYY' (e.g., 'January 1, 2024 to December 31, 2024')."
  },
  {
    label: "Working Capital",
    field: "Working Capital",
    prompt: "Extract working capital if explicitly stated in the document. If not found, return null. Do NOT calculate it."
  }
];

const PRESETS_LEGAL = [
  {
    label: "Document Type",
    field: "Document Type",
    prompt: "Identify the type of legal document (e.g., agreement, contract, NDA, lease, policy, judgment)."
  },
  {
    label: "Document Title",
    field: "Document Title",
    prompt: "Extract the full title of the document as stated on the first page."
  },
  {
    label: "Effective Date",
    field: "Effective Date",
    prompt: "Extract the effective date of the agreement. Return in format MM/DD/YYYY."
  },
  {
    label: "Execution Date",
    field: "Execution Date",
    prompt: "Extract the date on which the document was signed. Return in format MM/DD/YYYY."
  },
  {
    label: "Governing Law",
    field: "Governing Law",
    prompt: "Extract the governing law clause from the document. Return the jurisdiction or state that governs the agreement."
  },
  {
    label: "Jurisdiction",
    field: "Jurisdiction",
    prompt: "Extract the jurisdiction clause from the document. Return the location where legal disputes would be resolved."
  },
  {
    label: "Parties Involved",
    field: "Parties Involved",
    prompt: "Extract the names of all parties involved in the agreement. Return as an array of strings."
  },
  {
    label: "Addresses",
    field: "Addresses",
    prompt: "Extract the addresses of all parties involved. Return as an array of strings."
  },
  {
    label: "Terms and Conditions",
    field: "Terms and Conditions",
    prompt: "Extract the main terms and conditions of the agreement. Return as a summarized string or array of key points."
  },
  {
    label: "Scope of Agreement",
    field: "Scope of Agreement",
    prompt: "Extract the scope of the agreement. Return as a summarized string or array of key points describing what the agreement covers."
  }
];

const PRESETS_HEALTHCARE_DOCUMENTS = [
  {
    label: "Patient Name",
    field: "Patient Name",
    prompt: "Identify the patient’s full name from the document. Prefer the primary patient record section. Return only the name string.",
  },
  {
    label: "Patient ID / UHID",
    field: "Patient ID",
    prompt: "Extract the patient identifier such as UHID, Patient ID, or MRN. Return exact value as shown.",
  },
  {
    label: "Age / Gender",
    field: "Demographics",
    prompt: "Extract patient age and gender. Return in format: Age, Gender (e.g., 45, Male).",
  },
  {
    label: "Hospital Name",
    field: "Hospital Name",
    prompt: "Extract the name of the hospital or healthcare provider issuing this document.",
  },
  {
    label: "Doctor Name",
    field: "Doctor Name",
    prompt: "Extract the primary doctor or consultant name associated with the patient.",
  },
  {
    label: "Admission Date",
    field: "Admission Date",
    prompt: "Extract the hospital admission date. Return in standard date format.",
  },
  {
    label: "Discharge Date",
    field: "Discharge Date",
    prompt: "Extract the discharge date. Return in standard date format.",
  },
  {
    label: "Diagnosis",
    field: "Diagnosis",
    prompt: "Identify the final diagnosis or clinical impression. Prefer discharge summary or conclusion section. Return concise medical terms.",
  },
  {
    label: "Procedures / Treatments",
    field: "Procedures",
    prompt: "Extract procedures, surgeries, or treatments performed. Return as a list of medical procedures.",
  },
  {
    label: "Medications",
    field: "Medications",
    prompt: "Extract prescribed medications including name, dosage, and frequency if available. Return as structured list.",
  },
  {
    label: "Lab Test Results",
    field: "Lab Results",
    prompt: "Extract key lab test results including test name, value, and units. Return as structured array.",
  },
  {
    label: "Bill Number",
    field: "Bill Number",
    prompt: "Extract hospital bill or invoice number. Return exact value.",
  },
  {
    label: "Bill Date",
    field: "Bill Date",
    prompt: "Extract billing date from the document.",
  },
  {
    label: "Total Bill Amount",
    field: "Total Amount",
    prompt: "Extract the final total amount payable for the hospital bill. Prefer grand total or net payable.",
  },
  {
    label: "Room Charges",
    field: "Room Charges",
    prompt: "Extract room or bed charges. Include duration if mentioned.",
  },
  {
    label: "Doctor Fees",
    field: "Doctor Fees",
    prompt: "Extract consultation or doctor fees.",
  },
  {
    label: "Medicine Charges",
    field: "Medicine Charges",
    prompt: "Extract total cost of medicines billed.",
  },
  {
    label: "Lab Charges",
    field: "Lab Charges",
    prompt: "Extract laboratory or diagnostic charges.",
  },
  {
    label: "Surgery Charges",
    field: "Surgery Charges",
    prompt: "Extract surgical or operation charges if present.",
  },
  {
    label: "Insurance Provider",
    field: "Insurance Provider",
    prompt: "Extract insurance company name if mentioned.",
  },
  {
    label: "Policy Number",
    field: "Policy Number",
    prompt: "Extract insurance policy number if available.",
  },
  {
    label: "Claim Amount",
    field: "Claim Amount",
    prompt: "Extract claimed amount submitted to insurance.",
  },
  {
    label: "Approved Amount",
    field: "Approved Amount",
    prompt: "Extract amount approved by insurance if available.",
  },
  {
    label: "Discharge Summary",
    field: "Discharge Summary",
    prompt: "Extract a concise summary of patient condition, treatment given, and outcome from discharge summary section.",
  },
  {
    label: "Follow-up Instructions",
    field: "Follow-up",
    prompt: "Extract follow-up instructions including medications, lifestyle advice, or revisit schedule.",
  },
  {
    label: "Document Type",
    field: "Document Type",
    prompt: "Classify document type (e.g., hospital bill, discharge summary, lab report, prescription). Return single label.",
  }
];

const PRESETS_MSA_EXTRACTION = [
  {
    label: "Agreement Title",
    field: "Agreement Title",
    prompt: "Extract the full title of the agreement as stated on the first page. Return exact text.",
  },
  {
    label: "Effective Date",
    field: "Effective Date",
    prompt: "Identify the effective date of the agreement. Prefer phrases like 'Effective Date'. Return only the date.",
  },
  {
    label: "Execution Date",
    field: "Execution Date",
    prompt: "Extract the date on which the agreement was signed by the parties.",
  },
  {
    label: "Party A Name",
    field: "Party A",
    prompt: "Extract the full legal name of the first party. Prefer the introductory clause. Return exact name.",
  },
  {
    label: "Party B Name",
    field: "Party B",
    prompt: "Extract the full legal name of the second party. Return exact name.",
  },
  {
    label: "Party Roles",
    field: "Party Roles",
    prompt: "Identify roles of each party (e.g., Client, Service Provider, Vendor). Return mapping of party name to role.",
  },
  {
    label: "Registered Addresses",
    field: "Addresses",
    prompt: "Extract registered addresses of all parties. Return as structured list.",
  },
  {
    label: "Scope of Services",
    field: "Scope of Services",
    prompt: "Extract the scope of services describing what services are to be provided. Prefer 'Scope' or 'Services' section.",
  },
  {
    label: "Service Levels (SLA)",
    field: "Service Levels",
    prompt: "Extract any service level commitments such as uptime, response time, or performance metrics.",
  },
  {
    label: "Term / Duration",
    field: "Term",
    prompt: "Extract contract duration including start date and end date or duration period.",
  },
  {
    label: "Renewal Terms",
    field: "Renewal Terms",
    prompt: "Extract renewal or extension conditions including auto-renewal if mentioned.",
  },
  {
    label: "Payment Terms",
    field: "Payment Terms",
    prompt: "Extract payment terms including fees, schedule, and conditions. Preserve structure.",
  },
  {
    label: "Pricing / Fees",
    field: "Fees",
    prompt: "Extract pricing details, fees, or rate cards mentioned in the agreement.",
  },
  {
    label: "Invoicing Terms",
    field: "Invoicing Terms",
    prompt: "Extract invoicing frequency, billing cycle, and payment timelines.",
  },
  {
    label: "Termination Clause",
    field: "Termination",
    prompt: "Extract termination conditions including notice period and termination triggers.",
  },
  {
    label: "Confidentiality Clause",
    field: "Confidentiality",
    prompt: "Extract confidentiality or non-disclosure obligations between parties.",
  },
  {
    label: "Limitation of Liability",
    field: "Liability",
    prompt: "Extract limitation of liability clause including caps or exclusions.",
  },
  {
    label: "Indemnification",
    field: "Indemnification",
    prompt: "Extract indemnification obligations including which party indemnifies whom.",
  },
  {
    label: "Intellectual Property Rights",
    field: "IP Rights",
    prompt: "Extract clauses related to ownership of intellectual property created or used.",
  },
  {
    label: "Data Protection / Privacy",
    field: "Data Protection",
    prompt: "Extract data protection, privacy, or data handling clauses.",
  },
  {
    label: "Compliance Requirements",
    field: "Compliance",
    prompt: "Extract regulatory or legal compliance obligations mentioned.",
  },
  {
    label: "Dispute Resolution",
    field: "Dispute Resolution",
    prompt: "Extract dispute resolution mechanism such as arbitration, mediation, or courts.",
  },
  {
    label: "Governing Law",
    field: "Governing Law",
    prompt: "Extract governing law or jurisdiction clause.",
  },
  {
    label: "Force Majeure",
    field: "Force Majeure",
    prompt: "Extract force majeure clause including covered events.",
  },
  {
    label: "Assignment Clause",
    field: "Assignment",
    prompt: "Extract whether rights or obligations can be assigned to third parties.",
  },
  {
    label: "Subcontracting",
    field: "Subcontracting",
    prompt: "Extract terms related to subcontracting or third-party service providers.",
  },
  {
    label: "Amendments",
    field: "Amendments",
    prompt: "Extract how the agreement can be modified or amended.",
  },
  {
    label: "Exclusivity",
    field: "Exclusivity",
    prompt: "Extract exclusivity obligations if any.",
  },
  {
    label: "Penalties / Liquidated Damages",
    field: "Penalties",
    prompt: "Extract penalties, service credits, or liquidated damages.",
  },
  {
    label: "Signatories",
    field: "Signatories",
    prompt: "Extract names and titles of signatories.",
  },
  {
    label: "Signature Dates",
    field: "Signature Dates",
    prompt: "Extract dates associated with each signature.",
  },
  {
    label: "Document Type",
    field: "Document Type",
    prompt: "Classify document as Master Service Agreement (MSA) or related agreement.",
  }
];

const PRESETS_SOW_EXTRACTION = [
  {
    label: "Document Title",
    field: "Document Title",
    prompt: "Extract the full title of the document. Prefer first page header. Return exact text.",
  },
  {
    label: "SOW Reference Number",
    field: "SOW Number",
    prompt: "Extract the Statement of Work reference or identification number if available.",
  },
  {
    label: "Effective Date",
    field: "Effective Date",
    prompt: "Extract the effective or start date of this SOW. Return only the date.",
  },
  {
    label: "Related Agreement",
    field: "Master Agreement Reference",
    prompt: "Extract reference to the governing agreement (e.g., MSA number or title).",
  },
  {
    label: "Client Name",
    field: "Client",
    prompt: "Extract the client or customer name. Return full legal name.",
  },
  {
    label: "Service Provider Name",
    field: "Service Provider",
    prompt: "Extract the vendor/service provider name. Return full legal name.",
  },
  {
    label: "Project Name",
    field: "Project Name",
    prompt: "Extract project name or engagement title if mentioned.",
  },
  {
    label: "Scope of Work",
    field: "Scope",
    prompt: "Extract detailed description of work to be performed. Prefer 'Scope of Work' section.",
  },
  {
    label: "Deliverables",
    field: "Deliverables",
    prompt: "Extract all deliverables with descriptions. Return as structured list.",
  },
  {
    label: "Milestones",
    field: "Milestones",
    prompt: "Extract project milestones including names, dates, and associated deliverables. Return structured list.",
  },
  {
    label: "Timeline / Schedule",
    field: "Timeline",
    prompt: "Extract project timeline including start date, end date, and key phases.",
  },
  {
    label: "Service Location",
    field: "Location",
    prompt: "Extract location where services will be performed (onsite, offshore, or address).",
  },
  {
    label: "Resource Requirements",
    field: "Resources",
    prompt: "Extract details of required personnel, roles, or team composition.",
  },
  {
    label: "Roles & Responsibilities",
    field: "Responsibilities",
    prompt: "Extract responsibilities of each party. Return structured mapping if possible.",
  },
  {
    label: "Dependencies / Assumptions",
    field: "Dependencies",
    prompt: "Extract assumptions or dependencies required for successful execution.",
  },
  {
    label: "Pricing Model",
    field: "Pricing Model",
    prompt: "Identify pricing model (fixed price, time & materials, milestone-based).",
  },
  {
    label: "Fees / Cost",
    field: "Fees",
    prompt: "Extract total project cost or fee structure. Include breakdown if available.",
  },
  {
    label: "Payment Schedule",
    field: "Payment Schedule",
    prompt: "Extract payment schedule linked to milestones or timelines.",
  },
  {
    label: "Invoicing Terms",
    field: "Invoicing",
    prompt: "Extract invoicing frequency, billing process, and payment timelines.",
  },
  {
    label: "Acceptance Criteria",
    field: "Acceptance Criteria",
    prompt: "Extract criteria for acceptance of deliverables.",
  },
  {
    label: "Change Request Process",
    field: "Change Management",
    prompt: "Extract process for handling scope changes or change requests.",
  },
  {
    label: "Termination Conditions",
    field: "Termination",
    prompt: "Extract termination conditions specific to this SOW.",
  },
  {
    label: "Risk / Issues",
    field: "Risks",
    prompt: "Extract identified risks, issues, or mitigation plans.",
  },
  {
    label: "Service Level Agreements",
    field: "SLA",
    prompt: "Extract SLA metrics such as response time, uptime, or delivery timelines.",
  },
  {
    label: "Confidentiality Reference",
    field: "Confidentiality",
    prompt: "Extract confidentiality obligations or references to governing agreement.",
  },
  {
    label: "Signatories",
    field: "Signatories",
    prompt: "Extract names and titles of authorized signatories.",
  },
  {
    label: "Signature Dates",
    field: "Signature Dates",
    prompt: "Extract dates associated with signatures.",
  },
  {
    label: "Document Type",
    field: "Document Type",
    prompt: "Classify document as Statement of Work (SOW). Return single label.",
  }
];

// ── UTILS ─────────────────────────────────────────────────────────────────────
function highlight(json) {
  return json
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(
      /("(\\u[\da-fA-F]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
      (m) => {
        let cls = "jn";
        if (/^"/.test(m)) cls = /:$/.test(m) ? "jk" : "js";
        else if (/true|false/.test(m)) cls = "jb";
        else if (/null/.test(m)) cls = "jnu";
        return `<span class="${cls}">${m}</span>`;
      }
    );
}

let _idCounter = 0;
const nextId = () => ++_idCounter;

// ── NEW EXTRACTION UI ──────────────────────────────────────────────────────────
function NewExtractionUI({
  file,
  dataPoints,
  newField,
  setNewField,
  newPrompt,
  setNewPrompt,
  dragging,
  expanded,
  result,
  view,
  setView,
  loading,
  prog,
  error,
  selectedPreset,
  preset,
  verifyMode,
  fileInputRef,
  resultSecRef,
  copiedJSON,
  withPrompts,
  missingCount,
  canRun,
  resultEntries,
  resultFilename,
  verifyEntries,
  approvedCount,
  flaggedCount,
  pendingCount,
  verifiedFields,
  editedResult,
  flagNotes,
  pdfUrl,
  onDragOver,
  onDragLeave,
  onDrop,
  onFileChange,
  clearFile,
  addDataPoint,
  handlePresetChange,
  addPreset,
  removeDataPoint,
  updateDpField,
  updateDpPrompt,
  toggleExpand,
  runExtraction,
  copyJSON,
  downloadExcel,
  setFieldStatus,
  setFieldValue,
  setFieldNote,
  approveAll,
  saveJson,
  exportVerified,
  backToExtraction,
  setVerifyMode,
}) {
  return (
    <>
      {/* ══════════════════ VERIFY SCREEN ══════════════════ */}
      {verifyMode && result && (
        <div className="dv-root">
          {/* Top bar */}
          <div className="dv-topbar">
            <button className="dv-back-btn" onClick={backToExtraction}>
              <svg viewBox="0 0 24 24" fill="none" strokeWidth="2" stroke="currentColor" width="15" height="15">
                <path d="M19 12H5M12 5l-7 7 7 7" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Back
            </button>
            <div className="dv-topbar-center">
              <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="14" height="14">
                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
              <span className="dv-filename">{file?.name}</span>
              <div className="dv-topbar-stats">
                <span className="dv-stat approved">{approvedCount} approved</span>
                <span className="dv-stat flagged">{flaggedCount} flagged</span>
                <span className="dv-stat pending">{pendingCount} pending</span>
              </div>
            </div>
            <div className="dv-topbar-actions">
              <button className="dv-approve-all-btn" onClick={approveAll}>
                ✓ Approve All
              </button>
              <button className="dv-export-btn" onClick={saveJson}>
                Save
              </button>
              <button className="dv-export-btn" onClick={exportVerified}>
                ↓ Export Verified
              </button>
            </div>
          </div>

          {/* Split pane */}
          <div className="dv-split">
            {/* LEFT: PDF viewer */}
            <div className="dv-pdf-pane">
              <div className="dv-pane-label">
                <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="13" height="13">
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                </svg>
                Source Document
              </div>
              {pdfUrl ? (
                <iframe
                  className="dv-pdf-iframe"
                  src={pdfUrl}
                  title="PDF Viewer"
                />
              ) : (
                <div className="dv-pdf-fallback">PDF preview unavailable</div>
              )}
            </div>

            {/* RIGHT: Fields panel */}
            <div className="dv-fields-pane">
              <div className="dv-pane-label">
                <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="13" height="13">
                  <polyline points="9 11 12 14 22 4" />
                  <path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11" />
                </svg>
                Extracted Fields &nbsp;<span className="dv-field-count">{verifyEntries.length} fields</span>
              </div>
              <div className="dv-fields-list">
                {verifyEntries.map(([key, val], idx) => {
                  const status = verifiedFields[key] || "pending";
                  const isFlagged = status === "flagged";
                  return (
                    <div key={key} className={`dv-field-card dv-status-${status}`}>
                      <div className="dv-field-card-top">
                        <div className="dv-field-left">
                          <span className="dv-field-idx">{String(idx + 1).padStart(2, "0")}</span>
                          <span className="dv-field-key">{key}</span>
                        </div>
                        <div className="dv-field-actions">
                          <span className={`dv-status-badge dv-badge-${status}`}>
                            {status === "approved" ? "✓ Approved" : status === "flagged" ? "⚑ Flagged" : "● Pending"}
                          </span>
                          <button
                            className={`dv-btn-approve${status === "approved" ? " active" : ""}`}
                            onClick={() => setFieldStatus(key, status === "approved" ? "pending" : "approved")}
                            title="Approve"
                          >
                            ✓
                          </button>
                          <button
                            className={`dv-btn-flag${status === "flagged" ? " active" : ""}`}
                            onClick={() => setFieldStatus(key, status === "flagged" ? "pending" : "flagged")}
                            title="Flag for review"
                          >
                            ⚑
                          </button>
                        </div>
                      </div>
                      <textarea
                        className="dv-field-value"
                        value={editedResult[key] ?? ""}
                        onChange={(e) => setFieldValue(key, e.target.value)}
                        rows={Math.min(6, Math.max(2, (editedResult[key] || "").split("\n").length + 1))}
                        placeholder="null"
                      />
                      {isFlagged && (
                        <div className="dv-flag-note-wrap">
                          <input
                            className="dv-flag-note-input"
                            placeholder="Add a note about this issue…"
                            value={flagNotes[key] || ""}
                            onChange={(e) => setFieldNote(key, e.target.value)}
                          />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ══════════════════ NORMAL EXTRACTION SCREEN ══════════════════ */}
      {!verifyMode && (
        <div className="de-wrap">


          <div className="de-surface-2">
            {/* ── STEP 1: UPLOAD ── */}
            <div
              className={`de-drop-zone${dragging ? " dragover" : ""}`}
              onDragOver={onDragOver}
              onDragLeave={onDragLeave}
              onDrop={onDrop}
            >
              <input type="file" accept=".pdf" ref={fileInputRef} onChange={onFileChange} />
              <div className="de-up-icon">
                <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.5">
                  <path
                    d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                    stroke="currentColor"
                  />
                </svg>
              </div>
              <div className="de-up-title">Drop your PDF here or click to browse</div>
              <div className="de-up-sub">
                Accepts <b>.pdf</b> files
              </div>


              <div className={`de-file-info${file ? " show" : ""}`}>
                <svg className="de-file-info-font" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                </svg>
                <span className="de-file-info-font">{file?.name}</span>
                <span style={{ color: "var(--text-dim)" }}>
                  {file ? `(${(file.size / 1024 / 1024).toFixed(2)} MB)` : ""}
                </span>
                <span className="rm" onClick={clearFile}>✕</span>
              </div>
            </div>

            {/* ── STEP 2: DATA POINTS ── */}
            <div className="de-card">
              <div className="de-step-hd mt8">
                <div className="de-step-hd-sub">
                  <div>
                    <div className="de-step-title">Define Data Points &amp; Prompts</div>
                    <div className="de-step-sub">Each field has its own extraction instruction</div>
                  </div>
                  <button
                    className={`de-extract-btn${loading ? " loading" : ""}`}
                    onClick={runExtraction}
                    disabled={!canRun || loading}
                  >
                    <span className="de-btn-txt"><Play size={16} className="de-btn-icon" /> Run Extraction</span>
                    <span className="de-btn-spin" />
                  </button>
                </div>

              </div>
              <div className="de-card-surface">
                {/* Add row */}
                <div className="de-dp-add-labels">
                  <span>FIELD NAME</span>
                  <span>EXTRACTION PROMPT / INSTRUCTION</span>
                </div>
                <div className="de-dp-add-row">
                  <input
                    type="text"
                    className="de-dp-field-input"
                    placeholder="e.g. Policy Number"
                    autoComplete="off"
                    value={newField}
                    onChange={(e) => setNewField(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addDataPoint(); } }}
                  />
                  <textarea
                    className="de-dp-prompt-input"
                    rows={1}
                    placeholder='e.g. Extract only the policy number. Return in format "POL-XXXXXXXX". If not found return null.'
                    value={newPrompt}
                    onChange={(e) => setNewPrompt(e.target.value)}
                  />
                  <select
                    className="de-dp-add-btn"
                    onChange={handlePresetChange}
                    value={preset} // Keep it controlled so it always snaps back to the placeholder
                  >
                    <option value="Invoice Checking">Invoice Checking</option>
                    <option value="Financial Statements">Financial Statements</option>
                    <option value="Legal Documents">Legal Documents</option>
                    <option value="Health Care Documents">Health Care Documents</option>
                    <option value="MSA Extraction">MSA Extraction</option>
                    <option value="SOW Extraction">SOW Extraction</option>
                  </select>
                  <button className="de-dp-add-btn" onClick={() => addDataPoint()}>
                    + Add Field
                  </button>

                </div>

                {/* Data point list */}
                <div className="de-dp-list">
                  {dataPoints.length === 0 && (
                    <div className="de-dp-empty">
                      No data points added yet — add a field name and its extraction instruction above.
                    </div>
                  )}

                  {dataPoints.map((dp, i) => {
                    const hasPrompt = dp.prompt.trim().length > 0;
                    const isOpen = expanded[dp.id] ?? false;

                    return (
                      <div key={dp.id} className="de-dp-item">
                        <div className="de-dp-item-head">
                          <div className="de-dp-item-num">{String(i + 1).padStart(2, "0")}</div>
                          <div className="de-dp-item-name">
                            <input
                              value={dp.field}
                              placeholder="Field name"
                              onChange={(e) => updateDpField(dp.id, e.target.value)}
                              onKeyDown={(e) => { if (e.key === "Enter") e.preventDefault(); }}
                            />
                          </div>
                          <button
                            className={`de-dp-expand-btn${isOpen ? " open" : ""}`}
                            onClick={() => toggleExpand(dp.id)}
                          >
                            <span style={{ fontSize: "10px", letterSpacing: ".5px" }}>
                              {hasPrompt ? "PROMPT ✓" : "ADD PROMPT"}
                            </span>
                            <span className="de-arrow">▾</span>
                          </button>
                          <button
                            className="de-dp-delete-btn"
                            onClick={() => removeDataPoint(dp.id)}
                            title="Remove"
                          >
                            ✕
                          </button>
                        </div>

                        <div className={`de-dp-item-body${isOpen ? " open" : ""}`}>
                          <div className="de-dp-prompt-label">
                            <span className="pl-dot" /> Extraction Instruction
                          </div>
                          <textarea
                            className="de-dp-item-textarea"
                            placeholder="Describe exactly how to extract this field — format, fallback rules, where to look in the document, etc."
                            value={dp.prompt}
                            onChange={(e) => updateDpPrompt(dp.id, e.target.value)}
                          />
                          <div className="de-dp-prompt-status">
                            {hasPrompt ? (
                              <span className="de-pst-filled">✓ Prompt defined</span>
                            ) : (
                              <span className="de-pst-empty">⚠ No prompt — field will be sent without instruction</span>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Presets */}
                <div className="de-presets-row">
                  <span className="de-presets-label">Quick add:</span>
                  {selectedPreset.map((p) => (
                    <button
                      key={p.field}
                      className="de-preset-chip"
                      onClick={() => addPreset(p.field, p.prompt)}
                    >
                      {p.label}
                    </button>
                  ))}
                </div>

                {/* Summary bar */}
                <div className="de-summary-bar">
                  <div className="de-sb-stat">
                    Total Fields: <span className="sv">{dataPoints.length}</span>
                  </div>
                  <div className="de-sb-sep" />
                  <div className="de-sb-stat">
                    With Prompts: <span className="sv ok">{withPrompts}</span>
                  </div>
                  <div className="de-sb-sep" />
                  <div className="de-sb-stat">
                    Missing Prompts:{" "}
                    <span className={`sv ${missingCount > 0 ? "warn" : "ok"}`}>{missingCount}</span>
                  </div>
                </div>
              </div>
            </div>




            {/* ── RUN BAR ── */}
            <div className="de-run-bar">
              <div className="de-run-info">
                <div>
                  PDF: <span className="rv">{file ? file.name : "—"}</span>
                </div>
                <div>
                  Fields: <span className="rv">{dataPoints.length}</span>
                  &nbsp;·&nbsp; Backend: <span className="rv">localhost:5000</span>
                </div>
              </div>

            </div>

            {/* ── PROGRESS ── */}
            <div className="de-prog-msg">{prog.msg}</div>
            <div className={`de-prog-wrap${prog.show ? " show" : ""}`}>
              <div className="de-prog-bar" style={{ width: prog.pct + "%" }} />
            </div>

            {/* ── ERROR ── */}
            {error && <div className="de-error-box show">⚠ {error}</div>}

            {/* ── RESULTS ── */}
            <div ref={resultSecRef} className={`de-results-section${result ? " show" : ""}`}>
              <div className="de-res-header">
                <div className="de-res-title-g">
                  <div className="de-res-dot" />
                  <span className="de-res-title">Extraction Results</span>
                  <span className="de-res-count">{resultEntries.length} fields</span>
                </div>
                <div style={{ display: "flex", gap: "10px", alignItems: "center", flexWrap: "wrap" }}>
                  <div className="de-vtoggle">
                    <button
                      className={`de-vt${view === "table" ? " active" : ""}`}
                      onClick={() => setView("table")}
                    >
                      Table
                    </button>
                    <button
                      className={`de-vt${view === "json" ? " active" : ""}`}
                      onClick={() => setView("json")}
                    >
                      JSON
                    </button>
                  </div>
                  <div className="de-res-acts">
                    <button className="de-act-btn" onClick={() => setVerifyMode(true)}>
                      ↗ Review with PDF
                    </button>
                    <button className="de-act-btn" onClick={downloadExcel}>
                      ↓ Download Excel
                    </button>
                  </div>
                </div>
              </div>

              {/* Table view */}
              {view === "table" && (
                <div style={{ overflowX: "auto", padding: "20px 0" }}>
                  <table style={{
                    width: "100%",
                    borderCollapse: "collapse",
                    fontSize: "14px",
                    fontFamily: "var(--font-mono)"
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: "var(--bg-secondary)", borderBottom: "2px solid var(--border)" }}>
                        <th style={{ padding: "12px 16px", textAlign: "left", fontWeight: "600", color: "var(--text-primary)" }}>Field</th>
                        <th style={{ padding: "12px 16px", textAlign: "left", fontWeight: "600", color: "var(--text-primary)" }}>Value</th>
                      </tr>
                    </thead>
                    <tbody>
                      {resultEntries.map(([k, v], idx) => {
                        const isNull = v === null || v === undefined;
                        const cellValue = isNull ? "null" : typeof v === "object" ? JSON.stringify(v, null, 2) : String(v);
                        return (
                          <tr key={k} style={{ borderBottom: "1px solid var(--border)", backgroundColor: idx % 2 === 0 ? "transparent" : "rgba(255,255,255,0.02)" }}>
                            <td style={{ padding: "12px 16px", color: "var(--text-secondary)", fontWeight: "500", maxWidth: "300px", wordBreak: "break-word" }}>{k}</td>
                            <td style={{ padding: "12px 16px", color: isNull ? "var(--text-dim)" : "var(--text-primary)", maxWidth: "500px", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>{cellValue}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}

              {/* JSON view */}
              {view === "json" && (
                <div className="de-json-viewer">
                  <div className="de-jvt">
                    <div className="de-jv-dots">
                      <div className="de-jv-dot" />
                      <div className="de-jv-dot" />
                      <div className="de-jv-dot" />
                    </div>
                    <span className="de-jv-fn">{resultFilename}</span>
                    <span />
                  </div>
                  <pre
                    className="de-json-pre"
                    dangerouslySetInnerHTML={{
                      __html: result ? highlight(JSON.stringify(result, null, 2)) : "",
                    }}
                  />
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}

function SettingsPage() {
  const [activeTab, setActiveTab] = useState("Billings");
  const [contactMode, setContactMode] = useState("existing");
  const [additionalEmail, setAdditionalEmail] = useState("");
  const [showExtraCard, setShowExtraCard] = useState(false);
  const [primaryCard, setPrimaryCard] = useState({
    name: "Alex Johnson",
    expiry: "02 / 2028",
    number: "8269 9620 9292 2538",
    cvv: "1234",
  });
  const [extraCard, setExtraCard] = useState({
    name: "",
    expiry: "",
    number: "",
    cvv: "",
  });

  const billingRows = [
    { invoice: "DocExtract Pro", date: "Apr 14, 2026", amount: "$299", status: "Paid", tracking: "INV-2026-0414" },
    { invoice: "Extractions Add-on", date: "Apr 10, 2026", amount: "$89", status: "Pending", tracking: "INV-2026-0410" },
    { invoice: "Storage Add-on", date: "Mar 28, 2026", amount: "$40", status: "Paid", tracking: "INV-2026-0328" },
  ];

  const renderSimpleCard = (icon, title, sub, actionLabel = "Update") => {
    const Icon = icon;
    return (
      <div className="settings-profile-card">
        <div className="settings-card-title">
          <Icon size={16} />
          <span>{title}</span>
        </div>
        <p style={{ color: "#8d93a8", fontSize: "13px", marginBottom: "14px" }}>{sub}</p>
        <button className="settings-primary-btn">{actionLabel}</button>
      </div>
    );
  };

  const updatePrimaryCard = (field, value) => {
    setPrimaryCard((prev) => ({ ...prev, [field]: value }));
  };

  const updateExtraCard = (field, value) => {
    setExtraCard((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className="settings-shell">
      <div className="settings-wrap">
        <div className="settings-head">
          <h1>Settings</h1>
          <p>Manage your account settings and preferences.</p>
        </div>

        <div className="settings-tabs">
          {["My details", "Profile", "Password", "Billings", "Plan", "Email", "Notifications"].map((tab) => (
            <button
              key={tab}
              className={`settings-tab${tab === activeTab ? " active" : ""}`}
              onClick={() => setActiveTab(tab)}
            >
              {tab}
            </button>
          ))}
        </div>

        <div className="settings-main-card">
          {activeTab === "Billings" ? (
            <div className="settings-billing-detail-card">
              <div className="settings-billing-block">
                <h2>Payment Method</h2>
                <p>Update your billing details and address.</p>
              </div>

              <div className="settings-billing-grid">
                <div className="settings-billing-block">
                  <h3>Card Details</h3>
                  <p>Update your billing details and address.</p>
                  <button
                    className="settings-card-action"
                    onClick={() => setShowExtraCard((prev) => !prev)}
                  >
                    {showExtraCard ? "Hide additional card" : "+ Add another card"}
                  </button>
                </div>
                <div className="settings-card-form">
                  <label>
                    Name on your Card
                    <input
                      value={primaryCard.name}
                      onChange={(e) => updatePrimaryCard("name", e.target.value)}
                    />
                  </label>
                  <label>
                    Expiry
                    <input
                      value={primaryCard.expiry}
                      onChange={(e) => updatePrimaryCard("expiry", e.target.value)}
                    />
                  </label>
                  <label>
                    Card Number
                    <input
                      value={primaryCard.number}
                      onChange={(e) => updatePrimaryCard("number", e.target.value)}
                    />
                  </label>
                  <label>
                    CVV
                    <input
                      value={primaryCard.cvv}
                      onChange={(e) => updatePrimaryCard("cvv", e.target.value)}
                    />
                  </label>
                </div>
              </div>

              {showExtraCard && (
                <div className="settings-extra-card">
                  <div className="settings-billing-block">
                    <h3>Additional Card</h3>
                    <p>Add backup billing card details.</p>
                  </div>
                  <div className="settings-card-form">
                    <label>
                      Name on your Card
                      <input
                        placeholder="Enter cardholder name"
                        value={extraCard.name}
                        onChange={(e) => updateExtraCard("name", e.target.value)}
                      />
                    </label>
                    <label>
                      Expiry
                      <input
                        placeholder="MM / YYYY"
                        value={extraCard.expiry}
                        onChange={(e) => updateExtraCard("expiry", e.target.value)}
                      />
                    </label>
                    <label>
                      Card Number
                      <input
                        placeholder="0000 0000 0000 0000"
                        value={extraCard.number}
                        onChange={(e) => updateExtraCard("number", e.target.value)}
                      />
                    </label>
                    <label>
                      CVV
                      <input
                        placeholder="***"
                        value={extraCard.cvv}
                        onChange={(e) => updateExtraCard("cvv", e.target.value)}
                      />
                    </label>
                  </div>
                </div>
              )}

              <div className="settings-contact-block">
                <h3>Contact email</h3>
                <p>Where should invoices be sent?</p>
                <label className="settings-radio-row">
                  <input
                    type="radio"
                    name="contactEmailMode"
                    checked={contactMode === "existing"}
                    onChange={() => setContactMode("existing")}
                  />
                  <span>Send to the existing email</span>
                  <small>alex.johnson@company.com</small>
                </label>
                <label className="settings-radio-row">
                  <input
                    type="radio"
                    name="contactEmailMode"
                    checked={contactMode === "additional"}
                    onChange={() => setContactMode("additional")}
                  />
                  <span>Add another email address</span>
                </label>
                {contactMode === "additional" && (
                  <div className="settings-extra-email">
                    <label>
                      New billing email
                      <input
                        type="email"
                        placeholder="name@company.com"
                        value={additionalEmail}
                        onChange={(e) => setAdditionalEmail(e.target.value)}
                      />
                    </label>
                  </div>
                )}
              </div>

              <div className="settings-billing-card">
                <div className="settings-billing-head">
                  <h2>Billing History</h2>
                  <p>See your recent subscription and add-on invoices.</p>
                </div>
                <div className="settings-billing-table-wrap">
                  <table className="settings-billing-table">
                    <thead>
                      <tr>
                        <th>Invoice</th>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Tracking</th>
                      </tr>
                    </thead>
                    <tbody>
                      {billingRows.map((row) => (
                        <tr key={row.tracking}>
                          <td>{row.invoice}</td>
                          <td>{row.date}</td>
                          <td>{row.amount}</td>
                          <td>
                            <span className={`settings-status-badge ${row.status.toLowerCase()}`}>{row.status}</span>
                          </td>
                          <td>{row.tracking}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          ) : activeTab === "Profile" ? (
            <div className="settings-profile-card">
              <div className="settings-card-title">
                <User size={16} />
                <span>Profile</span>
              </div>

              <div className="settings-profile-grid">
                <div className="settings-field">
                  <span>Full Name</span>
                  <strong>Alex Johnson</strong>
                </div>
                <button className="settings-link-btn">Edit</button>

                <div className="settings-field">
                  <span>Email</span>
                  <strong>alex.johnson@company.com</strong>
                </div>
                <button className="settings-link-btn">Edit</button>

                <div className="settings-field">
                  <span>Organization</span>
                  <strong>Acme Corp</strong>
                </div>
                <button className="settings-link-btn">Edit</button>
              </div>

              <button className="settings-primary-btn">Update Profile</button>
            </div>
          ) : activeTab === "Notifications" ? (
            renderSimpleCard(Bell, "Notifications", "Manage extraction alerts and email preferences.", "Update Notification Preferences")
          ) : activeTab === "Password" ? (
            renderSimpleCard(Shield, "Security", "Password, two-factor authentication, and sessions.", "Update Security Settings")
          ) : activeTab === "Email" ? (
            renderSimpleCard(Bell, "Email Preferences", "Manage delivery settings for extraction summaries and alerts.", "Update Email Settings")
          ) : activeTab === "Plan" ? (
            renderSimpleCard(CreditCard, "Plan", "View and manage your active subscription plan and limits.", "Manage Plan")
          ) : activeTab === "My details" ? (
            renderSimpleCard(User, "My Details", "Personal details used across your DocExtract workspace.", "Update Details")
          ) : (
            renderSimpleCard(KeyRound, "API Keys", "Manage API access tokens for integrations.", "Manage API Keys")
          )}
        </div>
      </div>
    </div>
  );
}

function TemplatesPage({ onUseTemplate }) {
  const [templates, setTemplates] = useState([]);
  const [loadingTemplates, setLoadingTemplates] = useState(true);
  const [templatesError, setTemplatesError] = useState("");

  useEffect(() => {
    let isMounted = true;

    const fetchTemplates = async () => {
      setLoadingTemplates(true);
      setTemplatesError("");
      try {
        const response = await fetch("http://127.0.0.1:5000/api/templates");
        if (!response.ok) {
          throw new Error(`Failed to fetch templates (${response.status})`);
        }
        const data = await response.json();
        const list = Array.isArray(data) ? data : Array.isArray(data.templates) ? data.templates : [];
        if (isMounted) setTemplates(list);
      } catch (err) {
        if (isMounted) {
          setTemplates([]);
          setTemplatesError(err.message || "Failed to load templates.");
        }
      } finally {
        if (isMounted) setLoadingTemplates(false);
      }
    };

    fetchTemplates();
    return () => {
      isMounted = false;
    };
  }, []);

  const getFields = (template) => {
    if (Array.isArray(template.data_points)) {
      return template.data_points.map((dp) => (typeof dp === "string" ? dp : dp?.field || "")).filter(Boolean);
    }
    if (Array.isArray(template.fields)) return template.fields;
    return [];
  };

  const getUpdatedText = (template) => {
    const raw = template.updated_at || template.created_at || template.timestamp;
    if (!raw) return "Recently";
    const d = new Date(raw);
    if (Number.isNaN(d.getTime())) return "Recently";
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  const getDescription = (template, fields) => {
    if (template.description && String(template.description).trim()) return template.description;
    const lead = template.name || template.template_name || "This template";
    const fieldWords = fields.slice(0, 3).join(", ");
    return fieldWords
      ? `${lead} extraction focused on ${fieldWords.toLowerCase()}.`
      : `${lead} extraction configuration for document processing.`;
  };

  const getRelatedWords = (template, fields) => {
    const fromName = String(template.name || template.template_name || "")
      .split(/[\s-_]+/)
      .map((w) => w.trim())
      .filter((w) => w.length > 2);
    const fromFields = fields.slice(0, 4);
    return [...new Set([...fromName, ...fromFields])].slice(0, 6);
  };

  return (
    <div className="templates-shell">
      <div className="templates-head">
        <div>
          <h1>Templates</h1>
          <p>Reusable extraction configurations for common document types</p>
        </div>
        <button className="templates-new-btn">
          <Plus size={14} />
          New Template
        </button>
      </div>

      {loadingTemplates ? (
        <div className="templates-state">Loading templates...</div>
      ) : templatesError ? (
        <div className="templates-state error">{templatesError}</div>
      ) : templates.length === 0 ? (
        <div className="templates-state">No templates available from API.</div>
      ) : (
        <div className="templates-grid">
          {templates.map((template, idx) => {
            const fields = getFields(template);
            const visibleFields = fields.slice(0, 5);
            const moreCount = Math.max(fields.length - visibleFields.length, 0);
            return (
              <div
                className="template-card"
                key={template.id || template.name || idx}
                onClick={() => onUseTemplate?.(template)}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    onUseTemplate?.(template);
                  }
                }}
              >
                <div className="template-card-top">
                  <span className="template-icon">
                    <LayoutGrid size={15} />
                  </span>
                  <h3>{template.name || template.template_name || "Untitled Template"}</h3>
                  <p>{getDescription(template, fields)}</p>
                </div>

                <div className="template-tags">
                  {getRelatedWords(template, visibleFields).map((field) => (
                    <span key={field} className="template-tag">{field}</span>
                  ))}
                  {moreCount > 0 && <span className="template-tag">+{moreCount} more</span>}
                </div>

                <div className="template-card-foot">
                  <span><Hash size={12} /> {fields.length} fields</span>
                  <span><Clock3 size={12} /> {getUpdatedText(template)}</span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      onUseTemplate?.(template);
                    }}
                  >
                    Use
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ── COMPONENT ─────────────────────────────────────────────────────────────────
export default function DocExtract() {
  // State
  const [file, setFileState] = useState(null);
  const [dataPoints, setDataPoints] = useState([]);
  const [newField, setNewField] = useState("");
  const [newPrompt, setNewPrompt] = useState("");
  const [dragging, setDragging] = useState(false);
  const [expanded, setExpanded] = useState({});
  const [result, setResult] = useState(null);
  const [view, setView] = useState("cards");
  const [loading, setLoading] = useState(false);
  const [prog, setProg] = useState({ show: false, pct: 0, msg: "" });
  const [error, setError] = useState("");
  const [copiedJSON, setCopiedJSON] = useState(false);
  const [selectedPreset, setSelectedPreset] = useState([]);
  const [preset, setPreset] = useState("");
  const [activeNav, setActiveNav] = useState("dashboard");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [verifyMode, setVerifyMode] = useState(false);
  const [verifiedFields, setVerifiedFields] = useState({}); // { fieldKey: "approved"|"flagged"|"pending" }
  const [editedResult, setEditedResult] = useState({});     // { fieldKey: editedValue }
  const [flagNotes, setFlagNotes] = useState({});           // { fieldKey: noteString }
  const [pdfUrl, setPdfUrl] = useState(null);

  useEffect(() => {
    // Clear results when file or data points change
    setSelectedPreset(PRESETS_POLICY_CHECKING);
  }, []);

  const fileInputRef = useRef(null);
  const resultSecRef = useRef(null);

  // ── Derived ────────────────────────────────────────────────────────────────
  const withPrompts = dataPoints.filter((d) => d.prompt.trim()).length;
  const missingCount = dataPoints.length - withPrompts;
  const canRun =
    file &&
    dataPoints.length > 0 &&
    dataPoints.every((d) => d.field.trim() && d.prompt.trim());

  // ── File Handling ──────────────────────────────────────────────────────────
  const applyFile = useCallback((f) => {
    if (f && f.type === "application/pdf") setFileState(f);
  }, []);

  const clearFile = () => {
    setFileState(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const onDragOver = (e) => { e.preventDefault(); setDragging(true); };
  const onDragLeave = () => setDragging(false);
  const onDrop = (e) => { e.preventDefault(); setDragging(false); applyFile(e.dataTransfer.files[0]); };
  const onFileChange = (e) => { if (e.target.files[0]) applyFile(e.target.files[0]); };

  const useTemplateForExtraction = (template) => {
    const name = template?.name || template?.template_name || "";
    const apiDataPoints = Array.isArray(template?.data_points) ? template.data_points : [];
    const apiFields = Array.isArray(template?.fields) ? template.fields : [];
    const normalized = (apiDataPoints.length > 0 ? apiDataPoints : apiFields).map((item) => {
      if (typeof item === "string") {
        return { id: nextId(), field: item, prompt: "" };
      }
      return {
        id: nextId(),
        field: item?.field || item?.name || "",
        prompt: item?.prompt || item?.instruction || "",
      };
    }).filter((dp) => dp.field.trim());

    setDataPoints(normalized);
    setExpanded(Object.fromEntries(normalized.map((dp) => [dp.id, !dp.prompt])));
    setPreset(name);
    setResult(null);
    setError("");
    setVerifyMode(false);
    setActiveNav("extraction");
  };

  // ── Data Points ────────────────────────────────────────────────────────────
  const addDataPoint = (field, prompt) => {
    const f = (field ?? newField).trim();
    const p = (prompt ?? newPrompt).trim();
    if (!f) return;
    const id = nextId();
    setDataPoints((prev) => [...prev, { id, field: f, prompt: p }]);
    setExpanded((prev) => ({ ...prev, [id]: !p }));
    if (field === undefined) {
      setNewField("");
      setNewPrompt("");
    }
  };

  const handlePresetChange = (e) => {
    const presetValue = e.target.value;
    if (!presetValue) return;  // No selection

    if (presetValue === "Invoice Checking") {
      setSelectedPreset(PRESETS_POLICY_CHECKING);
    } else if (presetValue === "Financial Statements") {
      setSelectedPreset(PRESETS_FINANCE);
    }
    else if (presetValue === "Legal Documents") {
      setSelectedPreset(PRESETS_LEGAL);
    }
    else if (presetValue === "Health Care Documents") {
      setSelectedPreset(PRESETS_HEALTHCARE_DOCUMENTS);
    }
    else if (presetValue === "MSA Extraction") {
      setSelectedPreset(PRESETS_MSA_EXTRACTION);
    }
    else if (presetValue === "SOW Extraction") {
      setSelectedPreset(PRESETS_SOW_EXTRACTION);
    }
    else {
      return;
    }
    setPreset(presetValue);
  };

  const addPreset = (field, prompt) => {
    if (dataPoints.find((d) => d.field.toLowerCase() === field.toLowerCase())) return;
    addDataPoint(field, prompt);
  };

  const removeDataPoint = (id) => {
    setDataPoints((prev) => prev.filter((d) => d.id !== id));
    setExpanded((prev) => { const n = { ...prev }; delete n[id]; return n; });
  };

  const updateDpField = (id, val) => setDataPoints((prev) => prev.map((d) => (d.id === id ? { ...d, field: val } : d)));
  const updateDpPrompt = (id, val) => setDataPoints((prev) => prev.map((d) => (d.id === id ? { ...d, prompt: val } : d)));
  const toggleExpand = (id) => setExpanded((prev) => ({ ...prev, [id]: !prev[id] }));

  // ── Extraction ─────────────────────────────────────────────────────────────
  const runExtraction = async () => {
    const missing = dataPoints.filter((d) => !d.prompt.trim());
    if (missing.length > 0) {
      setError(
        `Missing prompts for: ${missing.map((d) => `"${d.field}"`).join(", ")}. Please add a prompt for every field.`
      );
      return;
    }

    setError("");
    setLoading(true);
    setProg({ show: true, pct: 8, msg: "Uploading PDF…" });

    const payload = dataPoints.map((d) => ({ field: d.field.trim(), prompt: d.prompt.trim() }));
    const fd = new FormData();
    fd.append("pdf", file);
    fd.append("data_points", JSON.stringify(payload));
    fd.append("preset", preset);

    try {
      setProg({ show: true, pct: 25, msg: "Extracting text from PDF (OCR if needed)…" });

      let resp;
      try {
        resp = await fetch("http://localhost:5000/api/extract", { method: "POST", body: fd });
      } catch (fetchErr) {
        throw new Error(`Network error: ${fetchErr.message}. Is the backend running on localhost:5000?`);
      }

      setProg({ show: true, pct: 70, msg: `Running per-field AI extraction (${payload.length} fields)…` });

      let data;
      try {
        data = await resp.json();
      } catch (jsonErr) {
        throw new Error(`Failed to parse response: ${jsonErr.message}`);
      }

      if (!resp.ok) throw new Error(data.error || `Server error ${resp.status}`);
      if (data.error) throw new Error(data.error);
      if (!data.data) throw new Error("Invalid response: no data field returned from server");

      setProg({ show: true, pct: 100, msg: "Rendering results…" });
      setResult(data.data);
      // ── Init verify state ──
      const initEdited = {};
      const initVerified = {};
      Object.entries(data.data).forEach(([k, v]) => {
        initEdited[k] = v === null || v === undefined ? "null" : typeof v === "object" ? JSON.stringify(v, null, 2) : String(v);
        initVerified[k] = "pending";
      });
      setEditedResult(initEdited);
      setVerifiedFields(initVerified);
      setFlagNotes({});
      // Build a blob URL for the PDF viewer
      if (file) {
        const url = URL.createObjectURL(file);
        setPdfUrl(url);
      }
      setTimeout(() => setProg({ show: false, pct: 0, msg: "" }), 500);
      setTimeout(() => setVerifyMode(true), 600);
    } catch (err) {
      setProg({ show: false, pct: 0, msg: "" });
      setError(err.message || "Extraction failed. Is the backend running on localhost:5000?");
    } finally {
      setLoading(false);
    }
  };

  // ── Copy / Download ────────────────────────────────────────────────────────
  const copyJSON = () => {
    if (!result) return;
    navigator.clipboard
      .writeText(JSON.stringify(result, null, 2))
      .then(() => { setCopiedJSON(true); setTimeout(() => setCopiedJSON(false), 1400); });
  };

  const downloadExcel = () => {
    if (!result) return;
    const wsData = [["Field", "Value"]];
    Object.entries(result).forEach(([k, v]) => {
      const cellValue = v === null || v === undefined ? "null" : typeof v === "object" ? JSON.stringify(v) : String(v);
      wsData.push([k, cellValue]);
    });
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    ws["!cols"] = [{ wch: 25 }, { wch: 50 }];
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Results");
    const filename = (file?.name?.replace(".pdf", "") || "result") + "_result.xlsx";
    XLSX.writeFile(wb, filename);
  };

  // ── Verify helpers ─────────────────────────────────────────────────────────
  const setFieldStatus = (key, status) =>
    setVerifiedFields((prev) => ({ ...prev, [key]: status }));

  const setFieldValue = (key, val) =>
    setEditedResult((prev) => ({ ...prev, [key]: val }));

  const setFieldNote = (key, note) =>
    setFlagNotes((prev) => ({ ...prev, [key]: note }));

  const approveAll = () =>
    setVerifiedFields((prev) => Object.fromEntries(Object.keys(prev).map((k) => [k, "approved"])));
  const saveJson = async () => {
    try {
      const out = {};

      Object.keys(editedResult).forEach((k) => {
        out[k] = {
          value: editedResult[k],
          status: verifiedFields[k] || "pending",
          note: flagNotes[k] || "",
        };
      });

      const payload = {
        file_name: file?.name || "",
        out: out,
      };

      const res = await fetch("http://localhost:5000/api/save_result_status", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (res.ok) {
        const result = await res.json();
        alert(result.message || "Results saved successfully to server.");
      }

      if (!res.ok) {
        throw new Error(`Server error ${res.status}`);
      }
    } catch (err) {
      console.error(err);
      alert("Failed to save results to server: " + err.message);
    }
  };

  const exportVerified = () => {
    const out = {};
    Object.keys(editedResult).forEach((k) => {
      out[k] = { value: editedResult[k], status: verifiedFields[k] || "pending", note: flagNotes[k] || "" };
    });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([JSON.stringify(out, null, 2)], { type: "application/json" }));
    a.download = (file?.name?.replace(".pdf", "") || "result") + "_verified.json";
    a.click();
  };

  const backToExtraction = () => {
    setVerifyMode(false);
  };

  // ── Render ─────────────────────────────────────────────────────────────────
  const resultEntries = result ? Object.entries(result) : [];
  const resultFilename = file ? file.name.replace(".pdf", "") + "_result.json" : "result.json";

  // ── Verify screen derived ──────────────────────────────────────────────────
  const verifyEntries = result ? Object.entries(editedResult) : [];
  const approvedCount = Object.values(verifiedFields).filter((s) => s === "approved").length;
  const flaggedCount = Object.values(verifiedFields).filter((s) => s === "flagged").length;
  const pendingCount = Object.values(verifiedFields).filter((s) => s === "pending").length;

  const navItems = [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: (
        <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="16" height="16">
          <rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" />
          <rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" />
        </svg>
      ),
    },
    {
      id: "extraction",
      label: "New Extraction",
      icon: (
        <svg viewBox="0 0 24 24" fill="none" strokeWidth="2" stroke="currentColor" width="16" height="16">
          <path d="M12 5v14M5 12h14" strokeLinecap="round" />
        </svg>
      ),
    },
    {
      id: "templates",
      label: "Templates",
      icon: (
        <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="16" height="16">
          <path d="M4 19.5A2.5 2.5 0 016.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15A2.5 2.5 0 016.5 2z" />
        </svg>
      ),
    },
    {
      id: "integrations",
      label: "Integrations",
      icon: (
        <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="16" height="16">
          <circle cx="8" cy="8" r="3" /><circle cx="16" cy="16" r="3" />
          <path d="M10.5 10.5l3 3" strokeLinecap="round" />
          <path d="M8 5V3M8 13v2M5 8H3M13 8h2" strokeLinecap="round" />
        </svg>
      ),
    },
    {
      id: "history",
      label: "History",
      icon: (
        <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="16" height="16">
          <path d="M12 8v4l3 3" strokeLinecap="round" />
          <path d="M3.05 11a9 9 0 1 0 .5-4" strokeLinecap="round" />
          <path d="M3 4v4h4" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      ),
    },
  ];

  return (
    <div className={`de-root${sidebarCollapsed ? " sidebar-collapsed" : ""}`}>

      {/* ── SIDEBAR ── */}
      <aside className="de-sidebar">
        <div className="de-sb-top">
          <div className="de-sb-logo">
            {!sidebarCollapsed && (
              <div className="de-sb-logo-inner">
                <div className="de-sb-logo-box">
                  <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.5" stroke="white" width="18" height="18">
                    <path d="M9 12h6M9 16h6M7 4H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V6a2 2 0 00-2-2h-2" />
                    <path d="M9 4h6a2 2 0 010 4H9a2 2 0 010-4z" />
                  </svg>
                </div>
                <span className="de-sb-brand">Doc<span>Extract</span></span>
              </div>
            )}
            <button className="de-sb-toggle" onClick={() => setSidebarCollapsed(v => !v)} title="Toggle sidebar">
              <svg
                viewBox="0 0 24 24"
                fill="none"
                strokeWidth="2"
                stroke="currentColor"
                width="18"
                height="18"
                style={{
                  transition: 'transform 0.3s ease',
                  transform: sidebarCollapsed ? 'rotate(180deg)' : 'rotate(0deg)'
                }}
              >
                <path d="M15 18l-6-6 6-6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>

          <nav className="de-sb-nav">
            {navItems.map((item) => (
              <button
                key={item.id}
                className={`de-sb-nav-item${activeNav === item.id ? " active" : ""}`}
                onClick={() => setActiveNav(item.id)}
                title={sidebarCollapsed ? item.label : ""}
              >
                <span className="de-sb-nav-icon">{item.icon}</span>
                {!sidebarCollapsed && <span className="de-sb-nav-label">{item.label}</span>}
              </button>
            ))}
          </nav>
        </div>

        <div className="de-sb-bottom">
          <button
            className={`de-sb-nav-item${activeNav === "settings" ? " active" : ""}`}
            onClick={() => setActiveNav("settings")}
            title={sidebarCollapsed ? "Settings" : ""}
          >
            <span className="de-sb-nav-icon">
              <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" stroke="currentColor" width="16" height="16">
                <circle cx="12" cy="12" r="3" />
                <path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z" />
              </svg>
            </span>
            {!sidebarCollapsed && <span className="de-sb-nav-label">Settings</span>}
          </button>

          {!sidebarCollapsed && (
            <div className="de-sb-usage">
              <div className="de-sb-usage-label">USAGE</div>
              <div className="de-sb-usage-bar-wrap">
                <div className="de-sb-usage-bar" style={{ width: "65%" }} />
              </div>
              <div className="de-sb-usage-text">650 / 1000 Extractions left</div>
            </div>
          )}
        </div>
      </aside>

      {/* ── MAIN ── */}
      <div className="de-main">
        {/* Conditional rendering based on activeNav */}
        {activeNav === "extraction" && (
          <NewExtractionUI
            file={file}
            dataPoints={dataPoints}
            newField={newField}
            setNewField={setNewField}
            newPrompt={newPrompt}
            setNewPrompt={setNewPrompt}
            dragging={dragging}
            expanded={expanded}
            result={result}
            view={view}
            setView={setView}
            loading={loading}
            prog={prog}
            error={error}
            selectedPreset={selectedPreset}
            preset={preset}
            verifyMode={verifyMode}
            fileInputRef={fileInputRef}
            resultSecRef={resultSecRef}
            copiedJSON={copiedJSON}
            withPrompts={withPrompts}
            missingCount={missingCount}
            canRun={canRun}
            resultEntries={resultEntries}
            resultFilename={resultFilename}
            verifyEntries={verifyEntries}
            approvedCount={approvedCount}
            flaggedCount={flaggedCount}
            pendingCount={pendingCount}
            verifiedFields={verifiedFields}
            editedResult={editedResult}
            flagNotes={flagNotes}
            pdfUrl={pdfUrl}
            onDragOver={onDragOver}
            onDragLeave={onDragLeave}
            onDrop={onDrop}
            onFileChange={onFileChange}
            clearFile={clearFile}
            addDataPoint={addDataPoint}
            handlePresetChange={handlePresetChange}
            addPreset={addPreset}
            removeDataPoint={removeDataPoint}
            updateDpField={updateDpField}
            updateDpPrompt={updateDpPrompt}
            toggleExpand={toggleExpand}
            runExtraction={runExtraction}
            copyJSON={copyJSON}
            downloadExcel={downloadExcel}
            setFieldStatus={setFieldStatus}
            setFieldValue={setFieldValue}
            setFieldNote={setFieldNote}
            approveAll={approveAll}
            saveJson={saveJson}
            exportVerified={exportVerified}
            backToExtraction={backToExtraction}
            setVerifyMode={setVerifyMode}
          />
        )}

        {/* Dashboard - Empty for now */}
        {activeNav === "dashboard" && (
          <Dashboard setActiveNav={setActiveNav} />
        )}

        {/* Templates - Empty for now */}
        {activeNav === "templates" && (
          <TemplatesPage onUseTemplate={useTemplateForExtraction} />
        )}

        {/* Integrations - Empty for now */}
        {activeNav === "integrations" && (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--text-dim)" }}>
            <h2>Integrations</h2>
            <p>Coming soon...</p>
          </div>
        )}

        {/* History - Empty for now */}
        {activeNav === "history" && (
          <History />
        )}

        {/* Settings - Empty for now */}
        {activeNav === "settings" && (
          <SettingsPage />
        )}
      </div> {/* end de-main */}
    </div>
  );
}